Implemented a moblimiter
plexusorg/Plex pull request #95
Opened 2024-05-30 02:23 UTC by notsceptor

_(This PR resolves #84)_

The mob limiter stores the ceiling value and the max limit in config and can be modified using a command.

It works on a per chunk basis, here are the default values:
`mob_limit_enabled`: true
`max_mobs_per_chunk`: 50
`mob_limit_ceiling`: 500

The usage for the command `/moblimit` is as follows:
 - `/moblimit` - Shows information about the limiter, whether it's enabled/disabled, the entities per chunk count, the max limit, the chunk coords
 - `/moblimit on` - Toggles the limiter on
 - `/moblimit off` - Toggles the limiter off
 - `/moblimit setmax <limit>` - Sets the max amount of mobs per chunk

2024-05-30 19:03 UTC, Telesphoreo requested changes

2024-05-30 19:03 UTC, Telesphoreo commented on server/src/main/java/dev/plex/command/impl/MobLimitCMD.java
> +                return Collections.singletonList("<limit>");
should not return the usage, just return nothing

2024-05-30 19:03 UTC, Telesphoreo commented on server/src/main/java/dev/plex/util/PlexUtils.java
> +    public static boolean isEntityLimitReached(Chunk chunk, int limit)
does this have to go in PlexUtils?

2024-05-30 19:03 UTC, Telesphoreo commented on server/src/main/java/dev/plex/command/impl/MobLimitCMD.java
> +                    return PlexUtils.messageComponent("invalidMobLimit");
is there anything in messages.yml that already checks for invalid numbers?

2024-05-30 22:20 UTC, notsceptor commented on server/src/main/java/dev/plex/command/impl/MobLimitCMD.java
> +            String status = plugin.config.getBoolean("entity_limit.mob_limit_enabled") ? "<green>Enabled" : "<red>Disabled";
there is but it's unformatted and wouldn't work properly in the way I want it to work

2024-05-30 22:21 UTC, notsceptor commented on server/src/main/java/dev/plex/command/impl/MobLimitCMD.java
> +            String chunkCoords = String.format("<gray>(<em><white>Chunk<gray>: <reset>%d, %d<gray>)", chunk.getX(), chunk.getZ());
added

2024-05-30 22:21 UTC, notsceptor commented on server/src/main/java/dev/plex/command/impl/MobLimitCMD.java
> +                return Collections.singletonList("<limit>");
changed

2024-05-30 22:21 UTC, notsceptor commented on server/src/main/java/dev/plex/util/PlexUtils.java
> +    public static boolean isEntityLimitReached(Chunk chunk, int limit)
moved into the listener

2024-05-30 22:21 UTC, notsceptor commented on server/src/main/java/dev/plex/command/impl/MobLimitCMD.java
> +                    return PlexUtils.messageComponent("invalidMobLimit");
used a preset parser and removed the invalidMobLimit

2024-05-31 20:41 UTC, Telesphoreo approved these changes

2024-05-31 20:41 UTC, merged